/**
 * Demo seed for the Continuum Fiscal Services enrollment portal.
 *
 * Everything here is invented. No real person, business, phone number, email
 * address or Medicaid identifier appears in this file.
 *
 * Run with:  npm run seed
 */
import { randomUUID } from "node:crypto";
import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { PrismaClient } from "@prisma/client";
import { documentsFor } from "../src/config/documents";
import {
  sendDailyDigest,
  sendEnrollmentReceivedEmail,
  sendStatusChangeEmail,
} from "../src/lib/email";

const prisma = new PrismaClient();
const UPLOAD_DIR = path.join(process.cwd(), "uploads");

/* ------------------------------------------------------------------ */
/* Tiny placeholder PDF generator                                      */
/* ------------------------------------------------------------------ */

function placeholderPdf(title: string, lines: string[]) {
  const esc = (s: string) =>
    s.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");

  const stream = [
    `BT /F1 16 Tf 72 720 Td (${esc(title)}) Tj ET`,
    ...lines.map((line, i) => `BT /F1 11 Tf 72 ${688 - i * 18} Td (${esc(line)}) Tj ET`),
  ].join("\n");

  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
    `<< /Length ${Buffer.byteLength(stream, "latin1")} >>\nstream\n${stream}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];

  let out = "%PDF-1.4\n";
  const offsets: number[] = [];
  objects.forEach((body, index) => {
    offsets.push(Buffer.byteLength(out, "latin1"));
    out += `${index + 1} 0 obj\n${body}\nendobj\n`;
  });

  const xref = Buffer.byteLength(out, "latin1");
  out += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets) out += `${String(offset).padStart(10, "0")} 00000 n \n`;
  out += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;

  return Buffer.from(out, "latin1");
}

const slug = (value: string) =>
  value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

async function writePlaceholder(enrolleeName: string, docLabel: string) {
  const originalName = `${slug(enrolleeName)}-${slug(docLabel)}.pdf`;
  const storedName = `${randomUUID()}__${originalName}`;
  const bytes = placeholderPdf(docLabel, [
    `Enrollee: ${enrolleeName}`,
    "Continuum Fiscal Services — sample document",
    "",
    "This is placeholder content generated by the demo seed script.",
    "It contains no real personal or health information.",
  ]);
  await writeFile(path.join(UPLOAD_DIR, storedName), bytes);
  return { originalName, storedName, size: bytes.byteLength, mimeType: "application/pdf" };
}

/* ------------------------------------------------------------------ */
/* Dates                                                               */
/* ------------------------------------------------------------------ */

const NOW = new Date();

function daysAgo(days: number, hour = 9, minute = 15) {
  const date = new Date(NOW);
  date.setDate(date.getDate() - days);
  date.setHours(hour, minute, 0, 0);
  return date;
}

function todayAt(hour: number, minute: number) {
  const date = new Date(NOW);
  date.setHours(hour, minute, 0, 0);
  return date > NOW ? new Date(NOW.getTime() - 60_000) : date;
}

/* ------------------------------------------------------------------ */
/* People                                                              */
/* ------------------------------------------------------------------ */

const ADMIN = {
  name: "Renee Calloway",
  email: "renee.calloway@continuumfiscal.example",
  phone: "(747) 555-0100",
};

const REPS = [
  { name: "Priya Raman", email: "priya.raman@continuumfiscal.example", phone: "(404) 555-0111" },
  { name: "Marcus Bell", email: "marcus.bell@continuumfiscal.example", phone: "(770) 555-0122" },
  { name: "Tanya Okonkwo", email: "tanya.okonkwo@continuumfiscal.example", phone: "(478) 555-0133" },
];

type Status =
  | "RECEIVED"
  | "ACKNOWLEDGED"
  | "IN_REVIEW"
  | "MISSING_INFO"
  | "PROCESSED"
  | "ACTIVE";

type SeedEnrollment = {
  type: "EMPLOYEE" | "VENDOR" | "PARTICIPANT";
  name: string;
  email: string;
  phone: string;
  programs: Array<"COMP" | "NOW" | "CCSP" | "SOURCE" | "ICWP">;
  status: Status;
  age: number;
  participantName?: string;
  repIndex?: number;
  repNameRaw?: string;
  repEmailRaw?: string;
  businessName?: string;
  contactName?: string;
  missingNote?: string;
  detour?: boolean;
  uploadsToday?: number;
};

const ENROLLMENTS: SeedEnrollment[] = [
  // ---- Employees -------------------------------------------------------
  {
    type: "EMPLOYEE", name: "Jordan Ellis", email: "jordan.ellis@example.com",
    phone: "(404) 555-0143", programs: ["COMP", "NOW"], status: "ACTIVE", age: 96,
    participantName: "Marcus Alvarado", repIndex: 0, detour: true,
  },
  {
    type: "EMPLOYEE", name: "Alicia Ferrer", email: "alicia.ferrer@example.com",
    phone: "(404) 555-0147", programs: ["NOW"], status: "IN_REVIEW", age: 12,
    participantName: "Dee Whitmore", repIndex: 0, uploadsToday: 1,
  },
  {
    type: "EMPLOYEE", name: "Samuel Otieno", email: "samuel.otieno@example.com",
    phone: "(770) 555-0151", programs: ["CCSP"], status: "MISSING_INFO", age: 21,
    participantName: "Harold Pryce", repIndex: 0,
    missingNote:
      "Page 2 of the Form I-9 is unsigned, and the supporting photo ID was cut off in the scan. Please re-upload both. We also still need the Georgia Form G-4.",
  },
  {
    type: "EMPLOYEE", name: "Bianca Ruiz", email: "bianca.ruiz@example.com",
    phone: "(478) 555-0158", programs: ["SOURCE"], status: "ACKNOWLEDGED", age: 6,
    participantName: "Nina Castellano", repIndex: 1,
  },
  {
    type: "EMPLOYEE", name: "Derrick Hale", email: "derrick.hale@example.com",
    phone: "(404) 555-0162", programs: ["ICWP"], status: "PROCESSED", age: 44,
    participantName: "Roy Sandiford", repIndex: 1,
  },
  {
    type: "EMPLOYEE", name: "Keisha Moreland", email: "keisha.moreland@example.com",
    phone: "(770) 555-0169", programs: ["COMP", "SOURCE"], status: "ACTIVE", age: 130,
    participantName: "Marcus Alvarado", repIndex: 1,
  },
  {
    type: "EMPLOYEE", name: "Tomas Vega", email: "tomas.vega@example.com",
    phone: "(478) 555-0174", programs: ["NOW"], status: "RECEIVED", age: 2,
    participantName: "Elaine Dorsey", repIndex: 2, uploadsToday: 1,
  },
  {
    type: "EMPLOYEE", name: "Hannah Wexler", email: "hannah.wexler@example.com",
    phone: "(404) 555-0180", programs: ["CCSP", "SOURCE"], status: "MISSING_INFO", age: 30,
    participantName: "Grady Lutz", repIndex: 2,
    missingNote:
      "The background check consent form is missing a date next to the signature, and we have no direct deposit authorization on file. Paper checks will be issued until one is received.",
  },
  {
    type: "EMPLOYEE", name: "Omar Siddiqui", email: "omar.siddiqui@example.com",
    phone: "(770) 555-0186", programs: ["SOURCE", "ICWP"], status: "IN_REVIEW", age: 17,
    participantName: "Nina Castellano", repIndex: 2,
  },
  {
    type: "EMPLOYEE", name: "Rebecca Lindgren", email: "rebecca.lindgren@example.com",
    phone: "(404) 555-0191", programs: ["ICWP"], status: "ACTIVE", age: 78,
    participantName: "Roy Sandiford", repIndex: 0,
  },
  {
    type: "EMPLOYEE", name: "Andre Coleman", email: "andre.coleman@example.com",
    phone: "(478) 555-0195", programs: ["COMP"], status: "PROCESSED", age: 38,
    participantName: "Harold Pryce", repIndex: 1, detour: true,
  },
  {
    type: "EMPLOYEE", name: "Priscilla Nwosu", email: "priscilla.nwosu@example.com",
    phone: "(770) 555-0199", programs: ["NOW"], status: "RECEIVED", age: 1,
    participantName: "Elaine Dorsey",
    repNameRaw: "T. Okonkwo", repEmailRaw: "t.okonkwo@example.com",
    uploadsToday: 1,
  },

  // ---- Participants ----------------------------------------------------
  {
    type: "PARTICIPANT", name: "Marcus Alvarado", email: "marcus.alvarado@example.com",
    phone: "(404) 555-0210", programs: ["COMP", "NOW"], status: "ACTIVE", age: 150,
  },
  {
    type: "PARTICIPANT", name: "Nina Castellano", email: "nina.castellano@example.com",
    phone: "(770) 555-0214", programs: ["SOURCE"], status: "IN_REVIEW", age: 19,
  },
  {
    type: "PARTICIPANT", name: "Harold Pryce", email: "harold.pryce@example.com",
    phone: "(478) 555-0218", programs: ["CCSP"], status: "PROCESSED", age: 52,
  },
  {
    type: "PARTICIPANT", name: "Elaine Dorsey", email: "elaine.dorsey@example.com",
    phone: "(404) 555-0223", programs: ["NOW"], status: "ACKNOWLEDGED", age: 8,
  },
  {
    type: "PARTICIPANT", name: "Roy Sandiford", email: "roy.sandiford@example.com",
    phone: "(770) 555-0227", programs: ["ICWP"], status: "ACTIVE", age: 115,
  },
  {
    type: "PARTICIPANT", name: "Dee Whitmore", email: "dee.whitmore@example.com",
    phone: "(478) 555-0231", programs: ["NOW"], status: "MISSING_INFO", age: 26,
    missingNote:
      "IRS Form 2678 is signed but the employer identification number field is blank, so we cannot file it. Please re-upload a completed copy.",
  },
  {
    type: "PARTICIPANT", name: "Grady Lutz", email: "grady.lutz@example.com",
    phone: "(404) 555-0235", programs: ["CCSP"], status: "RECEIVED", age: 3,
  },

  // ---- Vendors ---------------------------------------------------------
  {
    type: "VENDOR", name: "Dana Whitfield", email: "ap@peachtreemobility.example",
    phone: "(404) 555-0240", programs: ["COMP", "NOW", "CCSP"], status: "ACTIVE", age: 140,
    businessName: "Peachtree Mobility Supply LLC", contactName: "Dana Whitfield",
  },
  {
    type: "VENDOR", name: "Leo Barnhart", email: "billing@savannahrespite.example",
    phone: "(912) 555-0244", programs: ["SOURCE"], status: "IN_REVIEW", age: 15,
    businessName: "Savannah Respite Partners", contactName: "Leo Barnhart",
    uploadsToday: 1,
  },
  {
    type: "VENDOR", name: "Ruth Kellerman", email: "office@chattahoocheehomemods.example",
    phone: "(706) 555-0248", programs: ["ICWP"], status: "MISSING_INFO", age: 33,
    businessName: "Chattahoochee Home Modifications", contactName: "Ruth Kellerman",
    missingNote:
      "The certificate of liability insurance on file expired last month. We need a current certificate before any invoices can be paid.",
  },
  {
    type: "VENDOR", name: "Vincent Moy", email: "vincent@athensadaptive.example",
    phone: "(706) 555-0252", programs: ["NOW", "ICWP"], status: "PROCESSED", age: 41,
    businessName: "Athens Adaptive Technology", contactName: "Vincent Moy",
  },
  {
    type: "VENDOR", name: "Gloria Estrada", email: "dispatch@maconcaretransport.example",
    phone: "(478) 555-0256", programs: ["CCSP"], status: "ACKNOWLEDGED", age: 9,
    businessName: "Macon Care Transport", contactName: "Gloria Estrada",
  },
  {
    type: "VENDOR", name: "Kwame Adjei", email: "hello@piedmontnutrition.example",
    phone: "(770) 555-0260", programs: ["COMP"], status: "RECEIVED", age: 4,
    businessName: "Piedmont Nutrition Services", contactName: "Kwame Adjei",
  },
];

/* ------------------------------------------------------------------ */
/* Status chains                                                       */
/* ------------------------------------------------------------------ */

const STATUS_NOTES: Record<Status, string> = {
  RECEIVED: "Enrollment submitted through the public portal.",
  ACKNOWLEDGED: "Packet logged by enrollment intake. Assigned to the review queue.",
  IN_REVIEW: "Specialist reviewing submitted documents against the program checklist.",
  MISSING_INFO: "Outstanding items requested from the enrollee.",
  PROCESSED: "All documents verified and keyed into payroll and accounts payable.",
  ACTIVE: "Setup complete. Cleared to begin services under the waiver program.",
};

function chainFor(target: Status, detour: boolean): Status[] {
  const base: Record<Status, Status[]> = {
    RECEIVED: ["RECEIVED"],
    ACKNOWLEDGED: ["RECEIVED", "ACKNOWLEDGED"],
    IN_REVIEW: ["RECEIVED", "ACKNOWLEDGED", "IN_REVIEW"],
    MISSING_INFO: ["RECEIVED", "ACKNOWLEDGED", "IN_REVIEW", "MISSING_INFO"],
    PROCESSED: ["RECEIVED", "ACKNOWLEDGED", "IN_REVIEW", "PROCESSED"],
    ACTIVE: ["RECEIVED", "ACKNOWLEDGED", "IN_REVIEW", "PROCESSED", "ACTIVE"],
  };
  const chain = [...base[target]];
  if (detour && chain.length > 3) {
    // A record that went out for missing info and came back.
    chain.splice(3, 0, "MISSING_INFO", "IN_REVIEW");
  }
  return chain;
}

/** How many required documents are on file at each stage. */
function documentCountFor(status: Status, total: number) {
  switch (status) {
    case "RECEIVED":
      return Math.min(1, total);
    case "ACKNOWLEDGED":
      return Math.ceil(total / 2);
    case "IN_REVIEW":
      return Math.max(total - 1, 1);
    case "MISSING_INFO":
      return Math.max(total - 2, 1);
    default:
      return total;
  }
}

const TYPE_PREFIX = { EMPLOYEE: "EMP", VENDOR: "VEN", PARTICIPANT: "PAR" } as const;

/* ------------------------------------------------------------------ */
/* Seed                                                                */
/* ------------------------------------------------------------------ */

async function main() {
  console.log("Clearing existing demo data…");
  await prisma.outboxEmail.deleteMany();
  await prisma.document.deleteMany();
  await prisma.statusEvent.deleteMany();
  await prisma.enrollment.deleteMany();
  await prisma.user.deleteMany();

  await rm(UPLOAD_DIR, { recursive: true, force: true });
  await mkdir(UPLOAD_DIR, { recursive: true });

  const admin = await prisma.user.create({
    data: { ...ADMIN, role: "ADMIN", createdAt: daysAgo(400) },
  });

  const reps = [];
  for (const rep of REPS) {
    reps.push(
      await prisma.user.create({
        data: { ...rep, role: "REP", createdAt: daysAgo(380) },
      }),
    );
  }

  const counters: Record<string, number> = { EMPLOYEE: 0, VENDOR: 0, PARTICIPANT: 0 };
  let documentTotal = 0;
  let todayTotal = 0;

  for (const seed of ENROLLMENTS) {
    counters[seed.type] += 1;
    const refId = `CFS-${TYPE_PREFIX[seed.type]}-${String(counters[seed.type]).padStart(4, "0")}`;
    const createdAt = daysAgo(seed.age, 9, 15);
    const rep = seed.repIndex !== undefined ? reps[seed.repIndex] : null;

    const enrollee = await prisma.user.create({
      data: {
        name: seed.name,
        email: seed.email,
        phone: seed.phone,
        role: "ENROLLEE",
        createdAt,
      },
    });

    const enrollment = await prisma.enrollment.create({
      data: {
        refId,
        type: seed.type,
        programs: { create: seed.programs.map((program) => ({ program })) },
        status: seed.status,
        name: seed.name,
        email: seed.email,
        phone: seed.phone,
        participantName: seed.participantName ?? null,
        repNameRaw: seed.repNameRaw ?? rep?.name ?? null,
        repEmailRaw: seed.repEmailRaw ?? rep?.email ?? null,
        businessName: seed.businessName ?? null,
        contactName: seed.contactName ?? null,
        enrolleeId: enrollee.id,
        repId: rep?.id ?? null,
        createdAt,
        updatedAt: createdAt,
      },
    });

    // --- status history ------------------------------------------------
    const chain = chainFor(seed.status, Boolean(seed.detour));
    const spanMs = Math.max(NOW.getTime() - createdAt.getTime(), 36 * 3600 * 1000);
    const stepMs = spanMs / (chain.length + 1);

    for (let index = 0; index < chain.length; index++) {
      const status = chain[index];
      const at = new Date(createdAt.getTime() + stepMs * index);
      const isLatestMissing =
        status === "MISSING_INFO" && index === chain.length - 1 && seed.missingNote;
      await prisma.statusEvent.create({
        data: {
          enrollmentId: enrollment.id,
          status,
          note: isLatestMissing
            ? seed.missingNote
            : status === "MISSING_INFO"
              ? "Items requested from the enrollee; enrollment placed on hold."
              : STATUS_NOTES[status],
          changedById: index === 0 ? enrollee.id : admin.id,
          createdAt: at,
        },
      });
    }

    const lastEventAt = new Date(createdAt.getTime() + stepMs * (chain.length - 1));

    // --- documents -----------------------------------------------------
    const required = documentsFor(seed.type);
    const howMany = documentCountFor(seed.status, required.filter((d) => d.required).length);
    const requiredDocs = required.filter((d) => d.required).slice(0, howMany);
    const optionalDoc =
      seed.status === "ACTIVE" || seed.status === "PROCESSED"
        ? required.find((d) => !d.required)
        : undefined;
    const toUpload = optionalDoc ? [...requiredDocs, optionalDoc] : requiredDocs;

    let uploadsTodayLeft = seed.uploadsToday ?? 0;

    for (let index = 0; index < toUpload.length; index++) {
      const doc = toUpload[index];
      const file = await writePlaceholder(seed.businessName ?? seed.name, doc.label);

      let uploadedAt: Date;
      if (uploadsTodayLeft > 0 && index === toUpload.length - 1) {
        uploadedAt = todayAt(8 + todayTotal, 5 + todayTotal * 7);
        uploadsTodayLeft -= 1;
        todayTotal += 1;
      } else {
        const window = Math.max(lastEventAt.getTime() - createdAt.getTime(), 3600 * 1000);
        uploadedAt = new Date(
          createdAt.getTime() + (window * (index + 1)) / (toUpload.length + 1),
        );
      }

      // Reps file roughly every third employee document; admins key in faxes.
      const uploader =
        seed.type === "EMPLOYEE" && rep && index % 3 === 2
          ? rep
          : index === 0 && seed.status === "ACTIVE"
            ? admin
            : enrollee;

      await prisma.document.create({
        data: {
          enrollmentId: enrollment.id,
          docKey: doc.key,
          label: doc.label,
          originalName: file.originalName,
          storedName: file.storedName,
          mimeType: file.mimeType,
          size: file.size,
          uploadedById: uploader.id,
          createdAt: uploadedAt,
        },
      });
      documentTotal += 1;
    }

    // --- outbox: confirmation + the latest status notification ---------
    const received = await sendEnrollmentReceivedEmail(enrollment.id);
    if (received) {
      await prisma.outboxEmail.update({
        where: { id: received.id },
        data: { createdAt },
      });
    }

    const latest = chain[chain.length - 1];
    if (latest !== "RECEIVED") {
      const note =
        latest === "MISSING_INFO" && seed.missingNote
          ? seed.missingNote
          : STATUS_NOTES[latest];
      const email = await sendStatusChangeEmail({
        enrollmentId: enrollment.id,
        status: latest,
        note,
        changedByName: admin.name,
      });
      if (email) {
        await prisma.outboxEmail.update({
          where: { id: email.id },
          data: { createdAt: lastEventAt },
        });
      }
    }
  }

  // Yesterday's digest, so the outbox shows what one looks like before the
  // demo presses the button.
  const yesterday = daysAgo(1, 18, 0);
  const { email: digestEmail } = await sendDailyDigest(yesterday);
  if (digestEmail) {
    await prisma.outboxEmail.update({
      where: { id: digestEmail.id },
      data: { createdAt: daysAgo(0, 7, 0) },
    });
  }

  const [users, enrollments, documents, emails] = await Promise.all([
    prisma.user.count(),
    prisma.enrollment.count(),
    prisma.document.count(),
    prisma.outboxEmail.count(),
  ]);

  console.log("");
  console.log("Seed complete:");
  console.log(`  users        ${users} (1 admin, ${REPS.length} reps, ${enrollments} enrollees)`);
  console.log(`  enrollments  ${enrollments}`);
  console.log(`  documents    ${documents} placeholder PDFs in ./uploads (${todayTotal} dated today)`);
  console.log(`  outbox       ${emails} messages`);
  console.log("");
  console.log(`  Admin login:  ${ADMIN.name} — pick them in the header switcher`);
  console.log(`  Reps:         ${REPS.map((r) => r.name).join(", ")}`);
  console.log("");
  void documentTotal;
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
